version: '3.8'

services:
  nibiru-chat-server:
    build:
      context: .
    container_name: nibiru-chat-server
    restart: always
    expose:
      - 3002
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NODE_OPTIONS: "--max-old-space-size=${MAX_OLD_SPACE_SIZE}"
    command: sh -c "npm run migrate up && npm run start"
    networks:
      - global

networks:
  global:
    external: true